import json
import urllib.parse
import urllib.request
import re
from datetime import datetime


def search_web(query: str, max_results: int = 5) -> list[dict]:
    """Search the web using DuckDuckGo HTML endpoint and return structured results."""
    try:
        encoded_query = urllib.parse.urlencode({"q": query})
        url = f"https://html.duckduckgo.com/html/?{encoded_query}"
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=10) as resp:
            html = resp.read().decode("utf-8", errors="ignore")

        results = []
        # Parse result blocks from DuckDuckGo HTML response
        blocks = re.findall(
            r'<a rel="nofollow" class="result__a" href="([^"]*)"[^>]*>(.*?)</a>.*?'
            r'<a class="result__snippet"[^>]*>(.*?)</a>',
            html, re.DOTALL,
        )
        for href, title, snippet in blocks[:max_results]:
            # Clean HTML tags from title and snippet
            clean_title = re.sub(r"<[^>]+>", "", title).strip()
            clean_snippet = re.sub(r"<[^>]+>", "", snippet).strip()
            # DuckDuckGo wraps URLs in a redirect - extract the actual URL
            parsed = urllib.parse.parse_qs(urllib.parse.urlparse(href).query)
            actual_url = parsed.get("uddg", [href])[0]
            results.append({
                "title": clean_title,
                "url": actual_url,
                "snippet": clean_snippet,
            })
        return results if results else [{"title": "No results found", "url": "", "snippet": f"No results for: {query}"}]
    except Exception as e:
        return [{"title": "Search unavailable", "url": "", "snippet": str(e)}]


def generate_report(title: str, sections: dict) -> str:
    """Build a formatted markdown report from title and sections.

    Args:
        title: Report title (e.g. "Idea Definition Report")
        sections: Dict of {section_heading: content_string}

    Returns:
        Formatted markdown string
    """
    lines = [
        f"# {title}",
        f"*Generated by Aikapsule on {datetime.now().strftime('%B %d, %Y')}*",
        "",
    ]
    for heading, content in sections.items():
        lines.append(f"## {heading}")
        lines.append(content)
        lines.append("")
    lines.append("---")
    lines.append("*Aikapsule - Validate any idea in minutes*")
    return "\n".join(lines)


# Tool definitions for Claude API tool_use
TOOLS = [
    {
        "name": "web_search",
        "description": (
            "Search the web for information about competitors, similar solutions, "
            "market data, or any relevant context about the user's idea. "
            "Use this when you need to find existing products, companies, or trends "
            "related to the idea being discussed."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The search query to find relevant information",
                }
            },
            "required": ["query"],
        },
    },
    {
        "name": "generate_report",
        "description": (
            "Generate a structured report when you have gathered enough information. "
            "For Phase 1 (Idea Definition), generate after understanding the problem, "
            "audience, solutions, importance, and differentiator. "
            "For Phase 2 (Validation Strategy), generate after creating validation "
            "questions, testing channels, and a plan. "
            "For Phase 3 (Build MVP), generate after scoping core features, timeline, "
            "and success metrics. "
            "For Phase 4 (Validate Market), generate after assessing PMF signals, "
            "pilot results, and iteration priorities. "
            "For Phase 5 (Growth & Scale), generate after building acquisition "
            "strategy, unit economics, roadmap, and hiring plan."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "description": "Report title, e.g. 'Idea Definition Report' or 'Validation Strategy Report'",
                },
                "sections": {
                    "type": "object",
                    "description": (
                        "Object where keys are section headings and values are "
                        "the markdown-formatted content for that section"
                    ),
                    "additionalProperties": {"type": "string"},
                },
            },
            "required": ["title", "sections"],
        },
    },
]


def handle_tool_call(tool_name: str, tool_input: dict) -> str:
    """Execute a tool call from Claude and return the result as a string."""
    if tool_name == "web_search":
        results = search_web(tool_input["query"])
        return json.dumps(results, indent=2)
    elif tool_name == "generate_report":
        report = generate_report(tool_input["title"], tool_input["sections"])
        return report
    else:
        return json.dumps({"error": f"Unknown tool: {tool_name}"})